import { sqlLiteral } from "./sql-shards.mjs";

export const TARGET_SCHEMA_VERSION = 1;

export const SOURCE_COLUMNS = {
  drops: [
    "drop_id",
    "fancy_id",
    "title",
    "description",
    "start_date",
    "end_date",
    "city",
    "country",
    "event_url",
    "year",
    "is_virtual",
    "is_private",
    "channel",
    "platform",
    "location_type",
    "timezone",
    "created_at",
  ],
  tokens: [
    "source_uid",
    "poap_id",
    "drop_id",
    "minted_on",
    "owner_address",
    "network",
    "transfer_count",
  ],
  email_reservation_stats: [
    "drop_id",
    "email_reservations_total",
    "email_reservations_minted",
    "email_reservations_unminted",
  ],
  snapshot_metadata: ["key", "value"],
};

export const SOURCE_DROP_COLUMNS = SOURCE_COLUMNS.drops;
export const DROP_COLUMNS = [...SOURCE_DROP_COLUMNS, "token_count", "has_artwork"];
export const TOKEN_COLUMNS = [
  "source_uid",
  "poap_id",
  "drop_id",
  "minted_on",
  "owner_address_norm",
  "network",
  "transfer_count",
];
export const DROP_STATS_COLUMNS = [
  "drop_id",
  "email_reservations_total",
  "email_reservations_minted",
  "email_reservations_unminted",
];
export const OWNER_STATS_COLUMNS = [
  "owner_address_norm",
  "token_count",
  "unique_drop_count",
  "first_minted_on",
  "last_minted_on",
];

export const CATALOG_PREPARE_SQL = `-- Generated by tools/archive-import. Do not edit.
-- Apply only to a fresh staging D1 database after catalog/0001_schema.sql.
-- Optional fixture rows are removed before snapshot rows are loaded.
PRAGMA foreign_keys = ON;
DELETE FROM drop_stats;
DELETE FROM drops;
DELETE FROM archive_meta;
`;

export const HOLDINGS_PREPARE_SQL = `-- Generated by tools/archive-import. Do not edit.
-- Apply only to a fresh staging D1 database after holdings/0001_schema.sql.
-- Optional fixture rows are removed. Data is emitted in clustered-key order; rebuilding
-- a multi-million-row secondary index is deliberately unnecessary.
DELETE FROM archive_meta;
DELETE FROM owner_stats;
DELETE FROM tokens;
`;

export function catalogFinalizeSql(metadata) {
  return `-- Generated by tools/archive-import. Do not edit.
-- Metadata is written last and acts as the readiness marker consumed by the API.
${archiveMetaInsertSql(metadata)}
`;
}

export function holdingsFinalizeSql(metadata) {
  return `-- Generated by tools/archive-import. Do not edit.
-- Metadata is written last and is checked against the catalog snapshot before
-- public owner requests are served.
${archiveMetaInsertSql(metadata)}
SELECT COUNT(*) AS imported_tokens FROM tokens;
SELECT COUNT(*) AS imported_owners FROM owner_stats;
`;
}

function archiveMetaInsertSql(metadata) {
  const rows = Object.entries(metadata)
    .sort(([left], [right]) => left.localeCompare(right, "en"))
    .map(([key, value]) => `  (${sqlLiteral(key)}, ${sqlLiteral(String(value))})`)
    .join(",\n");
  return `INSERT INTO archive_meta (key, value) VALUES
${rows};`;
}
