import { createHash } from "node:crypto";
import { createWriteStream } from "node:fs";
import { mkdir, stat } from "node:fs/promises";
import { basename, relative, resolve } from "node:path";

import { endWritable, invariant, writeWithBackpressure } from "./util.mjs";

const GENERATED_HEADER = "-- Generated by tools/archive-import. Do not edit.\n\n";

export function sqlLiteral(value) {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number") {
    invariant(Number.isSafeInteger(value), `Unsafe SQL integer: ${value}`);
    return String(value);
  }
  if (typeof value === "boolean") return value ? "1" : "0";
  invariant(typeof value === "string", `Unsupported SQL value type: ${typeof value}`);
  if (value.includes("\u0000")) {
    return `CAST(X'${Buffer.from(value, "utf8").toString("hex")}' AS TEXT)`;
  }
  return `'${value.replaceAll("'", "''")}'`;
}

export class SqlShardWriter {
  constructor({
    outputRoot,
    relativeDirectory,
    sequenceStart,
    label,
    table,
    columns,
    maxShardBytes,
    maxStatementBytes,
    rowsPerStatement,
  }) {
    this.outputRoot = resolve(outputRoot);
    this.directory = resolve(outputRoot, relativeDirectory);
    this.relativeDirectory = relativeDirectory;
    this.sequence = sequenceStart;
    this.label = label;
    this.table = table;
    this.columns = columns;
    this.maxShardBytes = maxShardBytes;
    this.maxStatementBytes = maxStatementBytes;
    this.rowsPerStatement = rowsPerStatement;
    this.pendingRows = [];
    this.pendingBytes = 0;
    this.current = null;
    this.artifacts = [];
    this.totalRows = 0;
    this.totalStatements = 0;
  }

  async add(values) {
    invariant(
      values.length === this.columns.length,
      `${this.table}: expected ${this.columns.length} values.`,
    );
    const tuple = `(${values.map(sqlLiteral).join(", ")})`;
    const minimumStatementBytes = Buffer.byteLength(this.#statement([tuple]));
    invariant(
      minimumStatementBytes <= this.maxStatementBytes,
      `${this.table}: one row needs ${minimumStatementBytes} SQL bytes (limit ${this.maxStatementBytes}).`,
    );

    const candidate = [...this.pendingRows, tuple];
    const candidateBytes = Buffer.byteLength(this.#statement(candidate));
    if (
      this.pendingRows.length > 0 &&
      (candidate.length > this.rowsPerStatement || candidateBytes > this.maxStatementBytes)
    ) {
      await this.flushStatement();
    }

    this.pendingRows.push(tuple);
    this.pendingBytes = Buffer.byteLength(this.#statement(this.pendingRows));
    if (this.pendingRows.length >= this.rowsPerStatement) await this.flushStatement();
    this.totalRows += 1;
  }

  async flushStatement() {
    if (this.pendingRows.length === 0) return;
    const statement = this.#statement(this.pendingRows);
    const byteLength = Buffer.byteLength(statement);
    invariant(
      byteLength <= this.maxStatementBytes,
      `${this.table}: statement exceeds configured limit.`,
    );

    if (this.current && this.current.byteLength + byteLength > this.maxShardBytes) {
      await this.#closeCurrent();
    }
    if (!this.current) await this.#openNext();
    await this.#write(statement);
    this.current.statementCount += 1;
    this.current.rowCount += this.pendingRows.length;
    this.totalStatements += 1;
    this.pendingRows = [];
    this.pendingBytes = 0;
  }

  async close() {
    await this.flushStatement();
    await this.#closeCurrent();
    return this.artifacts;
  }

  #statement(rows) {
    const columnList = this.columns.map((column) => `"${column}"`).join(", ");
    return `INSERT INTO "${this.table}" (${columnList}) VALUES\n  ${rows.join(",\n  ")};\n`;
  }

  async #openNext() {
    await mkdir(this.directory, { recursive: true });
    const fileName = `${String(this.sequence).padStart(6, "0")}_${this.label}.sql`;
    this.sequence += 1;
    const filePath = resolve(this.directory, fileName);
    const stream = createWriteStream(filePath, { flags: "wx" });
    const hash = createHash("sha256");
    this.current = {
      filePath,
      stream,
      hash,
      byteLength: 0,
      rowCount: 0,
      statementCount: 0,
    };
    await this.#write(GENERATED_HEADER);
  }

  async #write(value) {
    const bytes = Buffer.byteLength(value);
    this.current.hash.update(value);
    this.current.byteLength += bytes;
    await writeWithBackpressure(this.current.stream, value);
  }

  async #closeCurrent() {
    if (!this.current) return;
    await endWritable(this.current.stream);
    this.artifacts.push({
      path: relative(this.outputRoot, this.current.filePath).replaceAll("\\", "/"),
      byteLength: this.current.byteLength,
      sha256: this.current.hash.digest("hex"),
      rowCount: this.current.rowCount,
      statementCount: this.current.statementCount,
      kind: "d1-sql",
      table: this.table,
    });
    this.current = null;
  }
}

export async function writeStaticArtifact(outputRoot, relativePath, contents, metadata = {}) {
  const filePath = resolve(outputRoot, relativePath);
  await mkdir(resolve(filePath, ".."), { recursive: true });
  const stream = createWriteStream(filePath, { flags: "wx" });
  const hash = createHash("sha256");
  hash.update(contents);
  await writeWithBackpressure(stream, contents);
  await endWritable(stream);
  const fileStat = await stat(filePath);
  return {
    path: relativePath.replaceAll("\\", "/"),
    byteLength: fileStat.size,
    sha256: hash.digest("hex"),
    ...metadata,
  };
}

export class NdjsonWriter {
  constructor(outputRoot, relativePath, metadata = {}) {
    this.outputRoot = resolve(outputRoot);
    this.relativePath = relativePath;
    this.filePath = resolve(outputRoot, relativePath);
    this.metadata = metadata;
    this.stream = null;
    this.hash = createHash("sha256");
    this.byteLength = 0;
    this.rowCount = 0;
  }

  async open() {
    await mkdir(resolve(this.filePath, ".."), { recursive: true });
    this.stream = createWriteStream(this.filePath, { flags: "wx" });
  }

  async add(value) {
    invariant(this.stream, `NDJSON writer ${basename(this.filePath)} is not open.`);
    const line = `${JSON.stringify(value)}\n`;
    this.hash.update(line);
    this.byteLength += Buffer.byteLength(line);
    this.rowCount += 1;
    await writeWithBackpressure(this.stream, line);
  }

  async close() {
    invariant(this.stream, `NDJSON writer ${basename(this.filePath)} is not open.`);
    await endWritable(this.stream);
    this.stream = null;
    return {
      path: this.relativePath.replaceAll("\\", "/"),
      byteLength: this.byteLength,
      sha256: this.hash.digest("hex"),
      rowCount: this.rowCount,
      ...this.metadata,
    };
  }
}
